name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - name: Test
        run: go test -v ./...

      - name: Fuzz Block NewBlock
        run: go test ./internal/core -fuzz=FuzzBlockNewBlock -fuzztime=10m

      - name: Fuzz Block CalculateHash
        run: go test ./internal/core -fuzz=FuzzBlockCalculateHash -fuzztime=10m

      - name: Fuzz MerkleTree
        run: go test ./internal/core -fuzz=FuzzMerkleTree -fuzztime=10m

      - name: Fuzz Blockchain AddBlock
        run: go test ./internal/core -fuzz=FuzzBlockchainAddBlock -fuzztime=10m

      - name: Fuzz Blockchain ValidateBlock
        run: go test ./internal/core -fuzz=FuzzBlockchainValidateBlock -fuzztime=10m

      - name: Fuzz Blockchain CalculateHash
        run: go test ./internal/core -fuzz=FuzzBlockchainCalculateHash -fuzztime=10m
